go_library(
    name = 'display',
    srcs = [
        'display.go',
        'display_memory.go',
    ],
    deps = [
        '//goboye/utils:utils',
        '//third_party:go-sdl2',
    ],
    visibility = [
        '//goboye:main',
    ]
)