go_binary(
    name = 'main',
    srcs = [
        'main.go',
    ],
    deps = [
        '//goboye/memory',
        '//goboye/cpu',
        '//goboye/debugger/widgets',
        '//third_party:gocui'
    ],
)