go_library(
    name = 'widgets',
    srcs = [
        'disassembly_widget.go'
    ],
    visibility = [
        '//goboye/debugger/...',
    ],
    deps = [
        '//goboye/cpu',
        '//third_party:gocui',
    ]
)
